### ISSUE TITLE
Navigation slider doesn't display all routes, sometimes, on the Account page.

### ISSUE THREAD

**Issue by NathanWEdwards** [codeforbtv/baby-equipment-exchange#17]
When connected to Cloud Firebase (and signed in as the test@account.com user), the navigation slider doesn't display all navigable routes, sometimes, on the Account page.

Steps to reproduce:

1. Sign in.
2. Navigate to the Accounts page.
3. Select the edit button.
4. Open the navigation menu.
5. Repeat steps 2 through 4 several times.

![BEE_Navigation_Menu_Accounts_Edit](https://github.com/codeforbtv/baby-equipment-exchange/assets/112483617/f76ca223-ade8-4daa-89bf-07dbb1b989ec)

**Comment by bryanparmelee** [comment]
@NathanWEdwards I'm having trouble recreating this issue. This may have been happening before the UserContext was added to the header component, but now that the context PR has been merged this appears to be working as expected.

**Comment by NathanWEdwards** [comment]
I have been unable to reproduce the issue within the Firebase Emulator Suite and when the application is deployed to Firebase Hosting.
