### ISSUE TITLE
The Account and Donate pages do not validate authentication.

### ISSUE THREAD

**Issue by NathanWEdwards** [codeforbtv/baby-equipment-exchange#18]
The site's Account and Donate pages do not yet validate a user has been authenticated.

Steps to reproduce:
1. Verify the user is not currently authenticated on the app.
2. Navigate to http://\<hostname\>:\<port\>/account and http://\<hostname\>:\<port\>/donate .

**Comment by bryanparmelee** [comment]
@NathanWEdwards just submitted a PR (#19 ) to resolve this issue.

**Comment by NathanWEdwards** [comment]
[Pull Request 19](https://github.com/codeforbtv/baby-equipment-exchange/pull/19) introduces changes to require authentication.

The [Protected Route API feature](https://github.com/codeforbtv/baby-equipment-exchange/tree/protected-api-call) also guards the page to handle unauthenticated users from accessing pages.
