### ISSUE TITLE
The Account Edit page is not guarded

### ISSUE THREAD

**Issue by NathanWEdwards** [codeforbtv/baby-equipment-exchange#21]
The [Account edit](https://github.com/codeforbtv/baby-equipment-exchange/blob/main/src/app/account/edit/page.tsx#L73) page is not guarded. An unauthenticated user is able to access the account/edit page.

**Comment by maplegilbs** [comment]
@bryanparmelee do you want to incorporate this into your #19 pull request before merging?

**Comment by bryanparmelee** [comment]
That's the hope! Unfortunately this approach doesn't work in nested pages like account/edit in Next 13, so I've been working on a different solution.

**Comment by NathanWEdwards** [comment]
[Pull request 36](https://github.com/codeforbtv/baby-equipment-exchange/pull/36) introduces changes to protected the Account Edit page from user-less and unauthenticated access.
