### ISSUE TITLE
Set up to allow multiple user tier categories for a user

### ISSUE THREAD

**Issue by ksnielsen** [codeforbtv/baby-equipment-exchange#29]

**Comment by NathanWEdwards** [comment]
Acceptance criteria:
- Users can be assigned to multiple tiers/categories (e.g. 'admin', 'donor', 'aid-worker and donor', 'volunteer for organization 1 and admin for organization 2')


[Pull Request 22](https://github.com/codeforbtv/baby-equipment-exchange/pull/22) introduces support for [custom claims](https://firebase.google.com/docs/auth/admin/custom-claims). Custom Claims is a feature the Firebase SDK offers that assigns attributes to users. These assigned attributes are not visible without programmatic access. Additionally, custom claims are compatible with Firebase Security Rules.

Custom claims define attributes within a JSON object. _Claims_ represent names of attributes as JSON keys and the values of a claim is a JSON value.
