### ISSUE TITLE
Treat all users as “users” / “donors”, then track whether people are also admins or mutual aid workers in separate tables

### ISSUE THREAD

**Issue by ksnielsen** [codeforbtv/baby-equipment-exchange#31]

**Comment by NathanWEdwards** [comment]
Users should be able to be associated as _users_/_donors_, _admins_, and _aides_.

Acceptance criteria:
- A _donor_ role designates users as donors
- An _admin_ role designates users as admins
- An _aide_ role designates users as an _aide_
- Users can possess an _admin_, _aide_, and _donor_ role
- A user cannot create a donation without a _donor_ role

[Pull Request 22](https://github.com/codeforbtv/baby-equipment-exchange/pull/22) introduces support for [custom claims](https://firebase.google.com/docs/auth/admin/custom-claims). Custom Claims is a feature the Firebase SDK offers that assigns attributes to users. These assigned attributes are not visible without programmatic access. Additionally, custom claims are compatible with Firebase Security Rules.

When a new user is created, a 'donor' claim is assigned to a user.
