### ISSUE TITLE
Start with assuming people will be repeat donors

### ISSUE THREAD

**Issue by ksnielsen** [codeforbtv/baby-equipment-exchange#32]

**Comment by NathanWEdwards** [comment]
User stories:
- As a standard user having already donated, I would like to create a donation again
- As a user with an administrator account, I would like to facilitate the creation of multiple donations with the account
- As a volunteer, I need to be able to submit and process multiple donations a day within the application

Acceptance criteria:
- A user with donor access can submit multiple donation forms

[Pull Request 1](https://github.com/codeforbtv/baby-equipment-exchange/pull/1) introduces a Firebase Firestore Donation and Donation Details collection for storing donation information.

The donation creation process allows users with a _donor_ claim to create donations.

[Pull Request 43](https://github.com/codeforbtv/baby-equipment-exchange/pull/43) permits users to create donations from the site landing page and the Donation page.
