### ISSUE TITLE
Login page behavior when a user is signed-in

### ISSUE THREAD

**Issue by NathanWEdwards** [codeforbtv/baby-equipment-exchange#6]
Currently, when an authenticated user navigates to the login page, the user is prompted for credentials to sign-in.

![baby_equipment_exchange_login_page_visit_as_an_authenticated_user](https://github.com/codeforbtv/baby-equipment-exchange/assets/112483617/d0b5dd6b-d28c-401d-9d26-414d15fb6763)

**Comment by maplegilbs** [comment]
@NathanWEdwards this should be addressed in PR #11 as the issue was arising from where the auth functionality was being imported from after it was moved from the firebase-config file to api/firebase.ts

**Comment by maplegilbs** [comment]
@NathanWEdwards this should be handled in PR #11 - by way of redirecting an authenticated user back to the home page should they navigate to /login.  I'll leave this issue open until that request is merged.

**Comment by NathanWEdwards** [comment]
[Pull request 11](https://github.com/codeforbtv/baby-equipment-exchange/pull/11) introduces changes to navigate users to the home page.
