### ISSUE TITLE
Input fields and event behavior

### ISSUE THREAD

**Issue by NathanWEdwards** [codeforbtv/baby-equipment-exchange#9]
The login page has two fields _email_ and _password_ that update state based on OnChange events. Input from methods like autocomplete do not trigger OnChange events.

Updating input tags to update state when OnInput events occur may provide a more fluid user experience.

Example use case user scenario:
As a user, when selecting an input field within the web application and an auto-fill option is available, when I select the auto-fill option, the page should accept the auto-fill supplied text as input.

**Comment by bryanparmelee** [comment]
From what I gather, onChange behaves a little differently in React and appears to be what they recommend using. https://react.dev/reference/react-dom/components/select#props 
![Screen Shot 2023-08-14 at 4 00 16 PM](https://github.com/codeforbtv/baby-equipment-exchange/assets/90424427/52315b43-d145-4be9-a0ec-4d20dfb6e1ae)

That said, I think these input fields should include an autoFill attribute. I added that to each and was able login using autofill in Chrome, Safari and Firefox, but I'm happy to use onInput instead if that's what we prefer.

**Comment by NathanWEdwards** [comment]
Input field events are following best practices.
